image: Visual Studio 2017
configuration: Release

before_build:
  ## Download nasm
  - cd %APPVEYOR_BUILD_FOLDER%
  - appveyor DownloadFile https://www.nasm.us/pub/nasm/releasebuilds/2.14.02/win64/nasm-2.14.02-win64.zip -FileName nasm.zip
  - 7z e -y nasm.zip
  ## Prepare cmake
  - mkdir cmake_build
  - cd cmake_build
  - cmake --version

build_script: cmake c:\projects\mozjpeg

artifacts:
 - path: cmake_build\Release\**\*.*
